plugins { id 'com.android.application' }
android {
    namespace 'com.jt600.sensortest'
    compileSdk 33
    buildToolsVersion '33.0.2'
    defaultConfig { applicationId 'com.jt600.sensortest'; minSdk 21; targetSdk 25; versionCode 2; versionName '1.1' }
    compileOptions { encoding 'UTF-8' }
    buildTypes { release { minifyEnabled false } }
    lint { disable 'ExpiredTargetSdkVersion' }
}
